(define (problem p1)
	(:domain hanoi)
	(:objects x y z - rod k1 k2 k3 k4 k5 - disk)
	(:init
	    (empty y)
	    (empty z)
	    (on-top k4 k5)
	    (on-top k3 k4)
	    (on-top k2 k3)
	    (on-top k1 k2)
	    (on-rod x k1)
	    (on-rod x k2)
	    (on-rod x k3)
	    (on-rod x k4)
	    (on-rod x k5)
	    (bigger k2 k1)
	    (bigger k3 k1)
	    (bigger k4 k1)
	    (bigger k5 k1)
	    (bigger k3 k2)
	    (bigger k4 k2)
	    (bigger k5 k2)
	    (bigger k4 k3)
	    (bigger k5 k3)
	    (bigger k5 k4)
	    (clear k1)
	    (on-floor k5)
	)
	(:goal
		(and
		    (on-rod z k1)
		    (on-rod z k2)
		    (on-rod z k3)
		    (on-rod z k4)
		    (on-rod z k5)
		)
	)
)
